### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by herrbischoff** [thedillonb/CodeHub#175] opened 2016-03-28 14:22 UTC
Every version of CodeHub I have used over the last year suffers from the same (annoying) problem: tapping a README, a menu item or basically any navigation element, crashes the app.

I cannot reproduce a sequence that always crashes it. Starting CodeHub again and tapping the same element works just as it should. The crashing appears to be random and not tied to any specific action.

I could not find a debug log option so I cannot attach crash reports which would probably be very helpful. Let me know what I can do to help.

iPhone 6 / iOS 9.3 / no Jailbreak or other shenanigans

**Comment by thedillonb** [comment] 2016-03-29 02:43
That's really unfortunate to hear. Although, honestly, I've had the app crash randomly too. I cannot, for the life of me, determine the root cause. My closest theory is poor resource management in Xamarin's framework. Regardless, every release I take the opportunity to clean up old code and pull new dependency versions in hope that I can one day rid the app of whatever causes it to randomly crash.

**Comment by herrbischoff** [comment] 2016-03-29 09:28
Interesting. I wasn't aware that you use Xamarin to build CodeHub. I don't know for sure but using C# for app development kind of feels off. As you are basically working in a non-native language, everything needs to be transpiled to different languages, which adds overhead of its own. I guess that also explains the UI that sometimes feels clunky and a little cheap. The curse of cross-platform development: that which tries to fit everywhere, fits nowhere proper.

Thanks for taking the time to reply to this issue. Maybe you could take this up with the Xamarin Team? As your code is Open Source, they should be able to assist you.

**Comment by thedillonb** [comment] 2016-03-29 15:20
Xamarin actually compiles down to native code - no transpilation. I originally started out when Objective-C was the only game in town - a language which I felt was one of the worst still in use (compared to the other modern languages out there). Swift, on the other hand, is one of the better languages out there. I've often toyed with the idea of re-writing it in swift, but have not had the time yet. 

I hope the UI doesn't feel too cheap as that's all native and of my creation ;) Regardless, I know what you mean about it feeling clunky. Unfortunately, I'm in too deep right now to re-write it. Someday perhaps.

**Comment by herrbischoff** [comment] 2016-03-29 19:16
Thanks for giving me some more background information. I understand completely. As much as passion projects would deserve more attention, one has to make ends meet. Don't worry, the UI is not cheap overall — just certain places where the whole experience would need more polish and love. Having said that, I'd be more than happy to lend a hand now and then in rethinking the UI. Also, sometime during this year, I'm going to dive into Swift and iOS development (I know what you mean regarding Objective-C...) so maybe, just maybe this could be a nice project to learn on. I'm all up for it, should you find the time.

**Comment by thedillonb** [comment] 2016-04-15 00:13
I think I've resolved most of the random crashes in the latest version released today (2.9.1). After collecting error reports for some time I think I managed to eliminate some of the corner cases that were being hit. I'm going to close this and continue to open more specific crashes as they come in.

**Closed by thedillonb** 2016-04-15 00:13 UTC
Labels: bug
