### ISSUE TITLE
[3.0 Redesign] Auto-hide various sections if you dont have access to them

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#81] opened 2014-04-12 16:30 UTC
The Assigned, Milestone and Labels sections will be hidden if the Github user is not part of the repo.

**Comment by thedillonb** [comment] 2015-02-07 20:30
Any user should still be able to see who the issue is assigned to and what milestone they anticipate a release.

**Closed by thedillonb** 2015-02-07 20:30 UTC
Labels: CodeHub Redesign Version 3.0

**Comment by Shawzborne** [comment] 2015-02-07 20:44
That's not exactly what I meant

**Comment by thedillonb** [comment] 2015-02-08 03:44
Were you talking about when you create an issue? Then yeah, I added the functionaility to hide the fields you can't edit if you're not a collaborator.

(This is a repo I am not a collaborator)
![ios simulator screen shot feb 7 2015 10 42 31 pm](https://cloud.githubusercontent.com/assets/1644068/6095131/d942dbda-af1a-11e4-82c6-ac2e799398d7.png)

(This is a repo I am a collaborator)
![ios simulator screen shot feb 7 2015 10 42 44 pm](https://cloud.githubusercontent.com/assets/1644068/6095133/ddf2f746-af1a-11e4-91ea-7aacd6b43350.png)

**Comment by Shawzborne** [comment] 2015-02-08 03:54
Yup that's what I meant :)

**Comment by Shawzborne** [comment] 2015-02-08 03:55
Did you change your iMessage?

**Comment by thedillonb** [comment] 2015-02-08 04:46
I actually have an Android as a primary phone now. My iPhone is just for dev now, and is Jailbroken, so I have a lot of the OS features disabled.

**Comment by Shawzborne** [comment] 2015-02-08 06:15
Lol oh

**Comment by Shawzborne** [comment] 2015-02-08 16:27
I sent you an email about adding me to the testflght beta, I'm not sure if your same email address still works. thanks
