### ISSUE TITLE
Apple Dark Mode makes text unreadable

### ISSUE THREAD

**Issue by Hoidberg** [thedillonb/CodeHub#689] opened 2020-09-15 21:36 UTC

**Comment by TheTechRobo** [comment] 2020-09-15 21:51
Duplicate of #667. **Please** look through existing issues before submitting a new one, there have been too many issues repeating what was reported in May.

**Comment by ChristianPari** [comment] 2021-03-22 11:51
Create automation
When "CodeHub" is open/closed
  -> Toggle "Appearance" 
This will toggle from dark to light for you as you switch back and forth from the app

**Closed as completed** 2021-04-03 18:29 UTC
