### ISSUE TITLE
Add method to move / sort favourite repositories in sidebar

### ISSUE THREAD

**Issue by DavidHaslam** [thedillonb/CodeHub#285] opened 2017-05-17 09:12 UTC
Repositories in the side bar are not in sorted alphabetical order. 

Please consider adding method move any one up and down, with a possible further option to sort them in specified order.

**Comment by DavidHaslam** [comment] 2017-05-17 09:29
Sorry, this duplicates issue #260.

**Comment by thedillonb** [comment] 2017-05-22 03:29
Closing as dupe of #260

**Closed by thedillonb** 2017-05-22 03:29 UTC
