### ISSUE TITLE
When refreshing lines don't go all the way across the screen to the left side 

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#39] opened 2014-03-27 12:46 UTC
When refreshing lines don't go all the way across the screen to the left side 

http://i.imgur.com/zWJXeUL.jpg

**Comment by thedillonb** [comment] 2016-02-27 17:15
Fixed in the next version. The table view cells will adjust the lines based on their preference. Otherwise, the line lengths will abide by the iOS default. There will be some space (the lines will not go all the way across) but this is by design (apparently) as iOS is assigning default separator spaces.

**Closed by thedillonb** 2016-02-27 17:15 UTC
